# Project docker-compose.yml (for your Next.js app)
# version: '3.8'

services:
  claude-dork-portfolio-service-site-app:
    image: claude-dork-portfolio-service-site-app:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`edinception.online`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portfolio.middlewares=secHeaders@file,rateLimit@file"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
    # Remove the ports mapping since Traefik handles it
    restart: always
    networks:
      - web
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
  web:
    external: true
  app-network:
    driver: bridge