# version: '3.8'

services:
  claude-dork-portfolio-service-site-app:
    image: claude-dork-portfolio-service-site-app:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.http.routers.dorkms-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.dorkms-http.entrypoints=http
      - traefik.http.routers.dorkms-http.middlewares=https-redirect
      - traefik.http.routers.dorkms-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.dorkms-https.entrypoints=https
      - traefik.http.routers.dorkms-https.tls=true
      - traefik.http.routers.dorkms-https.tls.certresolver=le
      - traefik.http.routers.dorkms-https.service=dorkms-service
      - traefik.http.services.dorkms-service.loadbalancer.server.port=3001
    networks:
      - web
      - traefik-public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  web:
    external: true
  traefik-public:
    driver: bridge