version: '3.8'

services:
  claude-dork-portfolio-service-site-app:
    image: claude-dork-portfolio-service-site-app:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`edinception.online`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3001"
    networks:
      - web
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  web:
    external: true
  app-network:
    driver: bridge